apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloapp
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helloapp
            image: busybox:1.28
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - date; echo Hello World!
          restartPolicy: OnFailure
