# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaschenpost-hello-world
  template:
    metadata:
      labels:
        app: flaschenpost-hello-world
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: hello-world-pod
        image: strm/helloworld-http:latest
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            host: 
            scheme: HTTP
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 1
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: flaschenpost-hello-world
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer